In [1]:
import torch

In [2]:
label = torch.tensor([1, 3, 4, 5])

In [32]:
label.squeeze_(-1)

tensor([1, 3, 4, 5])

In [33]:
onehot = torch.zeros((4, 10))

In [34]:
onehot[torch.arange(4), label] = 1

In [35]:
onehot

tensor([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [24]:
onehot

tensor([[0., 1., 0., 1., 1., 1., 0., 0., 0., 0.],
        [0., 1., 0., 1., 1., 1., 0., 0., 0., 0.],
        [0., 1., 0., 1., 1., 1., 0., 0., 0., 0.],
        [0., 1., 0., 1., 1., 1., 0., 0., 0., 0.]])